#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1022
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Utilidades
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ambiental")]
	public partial class DBAmbientalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertProvincia(Provincia instance);
    partial void UpdateProvincia(Provincia instance);
    partial void DeleteProvincia(Provincia instance);
    partial void InsertComuna(Comuna instance);
    partial void UpdateComuna(Comuna instance);
    partial void DeleteComuna(Comuna instance);
    partial void InsertRegion(Region instance);
    partial void UpdateRegion(Region instance);
    partial void DeleteRegion(Region instance);
    partial void InsertrbTipo(rbTipo instance);
    partial void UpdaterbTipo(rbTipo instance);
    partial void DeleterbTipo(rbTipo instance);
    partial void InsertrbPestana(rbPestana instance);
    partial void UpdaterbPestana(rbPestana instance);
    partial void DeleterbPestana(rbPestana instance);
    partial void InsertrbTipoDocPestania(rbTipoDocPestania instance);
    partial void UpdaterbTipoDocPestania(rbTipoDocPestania instance);
    partial void DeleterbTipoDocPestania(rbTipoDocPestania instance);
    #endregion
		
		public DBAmbientalDataContext() : 
				base(global::Datos.Properties.Settings.Default.AmbientalConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBAmbientalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBAmbientalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBAmbientalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBAmbientalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Provincia> Provincia
		{
			get
			{
				return this.GetTable<Provincia>();
			}
		}
		
		public System.Data.Linq.Table<Comuna> Comuna
		{
			get
			{
				return this.GetTable<Comuna>();
			}
		}
		
		public System.Data.Linq.Table<Region> Region
		{
			get
			{
				return this.GetTable<Region>();
			}
		}
		
		public System.Data.Linq.Table<rbTipo> rbTipo
		{
			get
			{
				return this.GetTable<rbTipo>();
			}
		}
		
		public System.Data.Linq.Table<rbPestana> rbPestana
		{
			get
			{
				return this.GetTable<rbPestana>();
			}
		}
		
		public System.Data.Linq.Table<rbTipoDocPestania> rbTipoDocPestania
		{
			get
			{
				return this.GetTable<rbTipoDocPestania>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Provincia")]
	public partial class Provincia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdProvincia;
		
		private string _Provincia1;
		
		private System.Nullable<int> _IdRegion;
		
		private System.Nullable<int> _Codigo;
		
		private EntitySet<Comuna> _Comuna;
		
		private EntityRef<Region> _Region;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdProvinciaChanging(int value);
    partial void OnIdProvinciaChanged();
    partial void OnProvincia1Changing(string value);
    partial void OnProvincia1Changed();
    partial void OnIdRegionChanging(System.Nullable<int> value);
    partial void OnIdRegionChanged();
    partial void OnCodigoChanging(System.Nullable<int> value);
    partial void OnCodigoChanged();
    #endregion
		
		public Provincia()
		{
			this._Comuna = new EntitySet<Comuna>(new Action<Comuna>(this.attach_Comuna), new Action<Comuna>(this.detach_Comuna));
			this._Region = default(EntityRef<Region>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProvincia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdProvincia
		{
			get
			{
				return this._IdProvincia;
			}
			set
			{
				if ((this._IdProvincia != value))
				{
					this.OnIdProvinciaChanging(value);
					this.SendPropertyChanging();
					this._IdProvincia = value;
					this.SendPropertyChanged("IdProvincia");
					this.OnIdProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Provincia", Storage="_Provincia1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Provincia1
		{
			get
			{
				return this._Provincia1;
			}
			set
			{
				if ((this._Provincia1 != value))
				{
					this.OnProvincia1Changing(value);
					this.SendPropertyChanging();
					this._Provincia1 = value;
					this.SendPropertyChanged("Provincia1");
					this.OnProvincia1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegion", DbType="Int")]
		public System.Nullable<int> IdRegion
		{
			get
			{
				return this._IdRegion;
			}
			set
			{
				if ((this._IdRegion != value))
				{
					if (this._Region.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdRegionChanging(value);
					this.SendPropertyChanging();
					this._IdRegion = value;
					this.SendPropertyChanged("IdRegion");
					this.OnIdRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int")]
		public System.Nullable<int> Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincia_Comuna", Storage="_Comuna", ThisKey="IdProvincia", OtherKey="IdProvincia")]
		public EntitySet<Comuna> Comuna
		{
			get
			{
				return this._Comuna;
			}
			set
			{
				this._Comuna.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Region_Provincia", Storage="_Region", ThisKey="IdRegion", OtherKey="IdRegion", IsForeignKey=true)]
		public Region Region
		{
			get
			{
				return this._Region.Entity;
			}
			set
			{
				Region previousValue = this._Region.Entity;
				if (((previousValue != value) 
							|| (this._Region.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Region.Entity = null;
						previousValue.Provincia.Remove(this);
					}
					this._Region.Entity = value;
					if ((value != null))
					{
						value.Provincia.Add(this);
						this._IdRegion = value.IdRegion;
					}
					else
					{
						this._IdRegion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Region");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comuna(Comuna entity)
		{
			this.SendPropertyChanging();
			entity.Provincia = this;
		}
		
		private void detach_Comuna(Comuna entity)
		{
			this.SendPropertyChanging();
			entity.Provincia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comuna")]
	public partial class Comuna : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdComuna;
		
		private string _Comuna1;
		
		private System.Nullable<int> _Codigo;
		
		private System.Nullable<int> _IdProvincia;
		
		private EntityRef<Provincia> _Provincia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdComunaChanging(int value);
    partial void OnIdComunaChanged();
    partial void OnComuna1Changing(string value);
    partial void OnComuna1Changed();
    partial void OnCodigoChanging(System.Nullable<int> value);
    partial void OnCodigoChanged();
    partial void OnIdProvinciaChanging(System.Nullable<int> value);
    partial void OnIdProvinciaChanged();
    #endregion
		
		public Comuna()
		{
			this._Provincia = default(EntityRef<Provincia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdComuna", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdComuna
		{
			get
			{
				return this._IdComuna;
			}
			set
			{
				if ((this._IdComuna != value))
				{
					this.OnIdComunaChanging(value);
					this.SendPropertyChanging();
					this._IdComuna = value;
					this.SendPropertyChanged("IdComuna");
					this.OnIdComunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Comuna", Storage="_Comuna1", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Comuna1
		{
			get
			{
				return this._Comuna1;
			}
			set
			{
				if ((this._Comuna1 != value))
				{
					this.OnComuna1Changing(value);
					this.SendPropertyChanging();
					this._Comuna1 = value;
					this.SendPropertyChanged("Comuna1");
					this.OnComuna1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int")]
		public System.Nullable<int> Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProvincia", DbType="Int")]
		public System.Nullable<int> IdProvincia
		{
			get
			{
				return this._IdProvincia;
			}
			set
			{
				if ((this._IdProvincia != value))
				{
					if (this._Provincia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProvinciaChanging(value);
					this.SendPropertyChanging();
					this._IdProvincia = value;
					this.SendPropertyChanged("IdProvincia");
					this.OnIdProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincia_Comuna", Storage="_Provincia", ThisKey="IdProvincia", OtherKey="IdProvincia", IsForeignKey=true)]
		public Provincia Provincia
		{
			get
			{
				return this._Provincia.Entity;
			}
			set
			{
				Provincia previousValue = this._Provincia.Entity;
				if (((previousValue != value) 
							|| (this._Provincia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Provincia.Entity = null;
						previousValue.Comuna.Remove(this);
					}
					this._Provincia.Entity = value;
					if ((value != null))
					{
						value.Comuna.Add(this);
						this._IdProvincia = value.IdProvincia;
					}
					else
					{
						this._IdProvincia = default(Nullable<int>);
					}
					this.SendPropertyChanged("Provincia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Region")]
	public partial class Region : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdRegion;
		
		private System.Nullable<int> _Codigo;
		
		private string _Region1;
		
		private EntitySet<Provincia> _Provincia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRegionChanging(int value);
    partial void OnIdRegionChanged();
    partial void OnCodigoChanging(System.Nullable<int> value);
    partial void OnCodigoChanged();
    partial void OnRegion1Changing(string value);
    partial void OnRegion1Changed();
    #endregion
		
		public Region()
		{
			this._Provincia = new EntitySet<Provincia>(new Action<Provincia>(this.attach_Provincia), new Action<Provincia>(this.detach_Provincia));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdRegion
		{
			get
			{
				return this._IdRegion;
			}
			set
			{
				if ((this._IdRegion != value))
				{
					this.OnIdRegionChanging(value);
					this.SendPropertyChanging();
					this._IdRegion = value;
					this.SendPropertyChanged("IdRegion");
					this.OnIdRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int")]
		public System.Nullable<int> Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Region", Storage="_Region1", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string Region1
		{
			get
			{
				return this._Region1;
			}
			set
			{
				if ((this._Region1 != value))
				{
					this.OnRegion1Changing(value);
					this.SendPropertyChanging();
					this._Region1 = value;
					this.SendPropertyChanged("Region1");
					this.OnRegion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Region_Provincia", Storage="_Provincia", ThisKey="IdRegion", OtherKey="IdRegion")]
		public EntitySet<Provincia> Provincia
		{
			get
			{
				return this._Provincia;
			}
			set
			{
				this._Provincia.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Provincia(Provincia entity)
		{
			this.SendPropertyChanging();
			entity.Region = this;
		}
		
		private void detach_Provincia(Provincia entity)
		{
			this.SendPropertyChanging();
			entity.Region = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rbTipo")]
	public partial class rbTipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipo;
		
		private string _nombreTipo;
		
		private string _grupo;
		
		private EntitySet<rbTipoDocPestania> _rbTipoDocPestania;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoChanging(int value);
    partial void OnidTipoChanged();
    partial void OnnombreTipoChanging(string value);
    partial void OnnombreTipoChanged();
    partial void OngrupoChanging(string value);
    partial void OngrupoChanged();
    #endregion
		
		public rbTipo()
		{
			this._rbTipoDocPestania = new EntitySet<rbTipoDocPestania>(new Action<rbTipoDocPestania>(this.attach_rbTipoDocPestania), new Action<rbTipoDocPestania>(this.detach_rbTipoDocPestania));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTipo
		{
			get
			{
				return this._idTipo;
			}
			set
			{
				if ((this._idTipo != value))
				{
					this.OnidTipoChanging(value);
					this.SendPropertyChanging();
					this._idTipo = value;
					this.SendPropertyChanged("idTipo");
					this.OnidTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreTipo", DbType="VarChar(200)")]
		public string nombreTipo
		{
			get
			{
				return this._nombreTipo;
			}
			set
			{
				if ((this._nombreTipo != value))
				{
					this.OnnombreTipoChanging(value);
					this.SendPropertyChanging();
					this._nombreTipo = value;
					this.SendPropertyChanged("nombreTipo");
					this.OnnombreTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupo", DbType="VarChar(100)")]
		public string grupo
		{
			get
			{
				return this._grupo;
			}
			set
			{
				if ((this._grupo != value))
				{
					this.OngrupoChanging(value);
					this.SendPropertyChanging();
					this._grupo = value;
					this.SendPropertyChanged("grupo");
					this.OngrupoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="rbTipo_rbTipoDocPestania", Storage="_rbTipoDocPestania", ThisKey="idTipo", OtherKey="idTipo")]
		public EntitySet<rbTipoDocPestania> rbTipoDocPestania
		{
			get
			{
				return this._rbTipoDocPestania;
			}
			set
			{
				this._rbTipoDocPestania.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_rbTipoDocPestania(rbTipoDocPestania entity)
		{
			this.SendPropertyChanging();
			entity.rbTipo = this;
		}
		
		private void detach_rbTipoDocPestania(rbTipoDocPestania entity)
		{
			this.SendPropertyChanging();
			entity.rbTipo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rbPestana")]
	public partial class rbPestana : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPestana;
		
		private string _nombrePestana;
		
		private EntitySet<rbTipoDocPestania> _rbTipoDocPestania;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPestanaChanging(int value);
    partial void OnidPestanaChanged();
    partial void OnnombrePestanaChanging(string value);
    partial void OnnombrePestanaChanged();
    #endregion
		
		public rbPestana()
		{
			this._rbTipoDocPestania = new EntitySet<rbTipoDocPestania>(new Action<rbTipoDocPestania>(this.attach_rbTipoDocPestania), new Action<rbTipoDocPestania>(this.detach_rbTipoDocPestania));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPestana", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPestana
		{
			get
			{
				return this._idPestana;
			}
			set
			{
				if ((this._idPestana != value))
				{
					this.OnidPestanaChanging(value);
					this.SendPropertyChanging();
					this._idPestana = value;
					this.SendPropertyChanged("idPestana");
					this.OnidPestanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrePestana", DbType="VarChar(200)")]
		public string nombrePestana
		{
			get
			{
				return this._nombrePestana;
			}
			set
			{
				if ((this._nombrePestana != value))
				{
					this.OnnombrePestanaChanging(value);
					this.SendPropertyChanging();
					this._nombrePestana = value;
					this.SendPropertyChanged("nombrePestana");
					this.OnnombrePestanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="rbPestana_rbTipoDocPestania", Storage="_rbTipoDocPestania", ThisKey="idPestana", OtherKey="idPestana")]
		public EntitySet<rbTipoDocPestania> rbTipoDocPestania
		{
			get
			{
				return this._rbTipoDocPestania;
			}
			set
			{
				this._rbTipoDocPestania.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_rbTipoDocPestania(rbTipoDocPestania entity)
		{
			this.SendPropertyChanging();
			entity.rbPestana = this;
		}
		
		private void detach_rbTipoDocPestania(rbTipoDocPestania entity)
		{
			this.SendPropertyChanging();
			entity.rbPestana = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rbTipoDocPestania")]
	public partial class rbTipoDocPestania : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipo;
		
		private int _idPestana;
		
		private System.Nullable<bool> _asocVigente;
		
		private EntityRef<rbPestana> _rbPestana;
		
		private EntityRef<rbTipo> _rbTipo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoChanging(int value);
    partial void OnidTipoChanged();
    partial void OnidPestanaChanging(int value);
    partial void OnidPestanaChanged();
    partial void OnasocVigenteChanging(System.Nullable<bool> value);
    partial void OnasocVigenteChanged();
    #endregion
		
		public rbTipoDocPestania()
		{
			this._rbPestana = default(EntityRef<rbPestana>);
			this._rbTipo = default(EntityRef<rbTipo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idTipo
		{
			get
			{
				return this._idTipo;
			}
			set
			{
				if ((this._idTipo != value))
				{
					if (this._rbTipo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipoChanging(value);
					this.SendPropertyChanging();
					this._idTipo = value;
					this.SendPropertyChanged("idTipo");
					this.OnidTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPestana", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idPestana
		{
			get
			{
				return this._idPestana;
			}
			set
			{
				if ((this._idPestana != value))
				{
					if (this._rbPestana.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPestanaChanging(value);
					this.SendPropertyChanging();
					this._idPestana = value;
					this.SendPropertyChanged("idPestana");
					this.OnidPestanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_asocVigente", DbType="Bit")]
		public System.Nullable<bool> asocVigente
		{
			get
			{
				return this._asocVigente;
			}
			set
			{
				if ((this._asocVigente != value))
				{
					this.OnasocVigenteChanging(value);
					this.SendPropertyChanging();
					this._asocVigente = value;
					this.SendPropertyChanged("asocVigente");
					this.OnasocVigenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="rbPestana_rbTipoDocPestania", Storage="_rbPestana", ThisKey="idPestana", OtherKey="idPestana", IsForeignKey=true)]
		public rbPestana rbPestana
		{
			get
			{
				return this._rbPestana.Entity;
			}
			set
			{
				rbPestana previousValue = this._rbPestana.Entity;
				if (((previousValue != value) 
							|| (this._rbPestana.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._rbPestana.Entity = null;
						previousValue.rbTipoDocPestania.Remove(this);
					}
					this._rbPestana.Entity = value;
					if ((value != null))
					{
						value.rbTipoDocPestania.Add(this);
						this._idPestana = value.idPestana;
					}
					else
					{
						this._idPestana = default(int);
					}
					this.SendPropertyChanged("rbPestana");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="rbTipo_rbTipoDocPestania", Storage="_rbTipo", ThisKey="idTipo", OtherKey="idTipo", IsForeignKey=true)]
		public rbTipo rbTipo
		{
			get
			{
				return this._rbTipo.Entity;
			}
			set
			{
				rbTipo previousValue = this._rbTipo.Entity;
				if (((previousValue != value) 
							|| (this._rbTipo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._rbTipo.Entity = null;
						previousValue.rbTipoDocPestania.Remove(this);
					}
					this._rbTipo.Entity = value;
					if ((value != null))
					{
						value.rbTipoDocPestania.Add(this);
						this._idTipo = value.idTipo;
					}
					else
					{
						this._idTipo = default(int);
					}
					this.SendPropertyChanged("rbTipo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
