//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.spanish {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.spanish.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Documento Asociado.
        /// </summary>
        internal static string agregarDocumentoAsociado {
            get {
                return ResourceManager.GetString("agregarDocumentoAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ámbito.
        /// </summary>
        internal static string ambito {
            get {
                return ResourceManager.GetString("ambito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ámbito.
        /// </summary>
        internal static string ambitoDocumentoAsociado {
            get {
                return ResourceManager.GetString("ambitoDocumentoAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo Adjunto.
        /// </summary>
        internal static string archivoAdjunto {
            get {
                return ResourceManager.GetString("archivoAdjunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destinatario.
        /// </summary>
        internal static string destinatario {
            get {
                return ResourceManager.GetString("destinatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string fecha {
            get {
                return ResourceManager.GetString("fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha C.I..
        /// </summary>
        internal static string fechaCI {
            get {
                return ResourceManager.GetString("fechaCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha no válida.
        /// </summary>
        internal static string fechaNoValida {
            get {
                return ResourceManager.GetString("fechaNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Flujo Documental .
        /// </summary>
        internal static string flujoDocumental {
            get {
                return ResourceManager.GetString("flujoDocumental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string limpiar {
            get {
                return ResourceManager.GetString("limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº Requerimiento.
        /// </summary>
        internal static string nRequerimiento {
            get {
                return ResourceManager.GetString("nRequerimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Fecha Ampliación.
        /// </summary>
        internal static string nuevafecha {
            get {
                return ResourceManager.GetString("nuevafecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número.
        /// </summary>
        internal static string numero {
            get {
                return ResourceManager.GetString("numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número C.I..
        /// </summary>
        internal static string numeroCI {
            get {
                return ResourceManager.GetString("numeroCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origen.
        /// </summary>
        internal static string origen {
            get {
                return ResourceManager.GetString("origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultado.
        /// </summary>
        internal static string resultado {
            get {
                return ResourceManager.GetString("resultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultado.
        /// </summary>
        internal static string resultadoDocumentoAsociado {
            get {
                return ResourceManager.GetString("resultadoDocumentoAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Supeditado.
        /// </summary>
        internal static string resultadoSupeditado {
            get {
                return ResourceManager.GetString("resultadoSupeditado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione.
        /// </summary>
        internal static string seleccioneDocumentoAsociado {
            get {
                return ResourceManager.GetString("seleccioneDocumentoAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tema.
        /// </summary>
        internal static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Documento.
        /// </summary>
        internal static string tipoDocumento {
            get {
                return ResourceManager.GetString("tipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string tipoDocumentoAsociado {
            get {
                return ResourceManager.GetString("tipoDocumentoAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Entrada.
        /// </summary>
        internal static string tipoEntrada {
            get {
                return ResourceManager.GetString("tipoEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Salida.
        /// </summary>
        internal static string tipoSalida {
            get {
                return ResourceManager.GetString("tipoSalida", resourceCulture);
            }
        }
    }
}
