using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Datos.Contantes
{
    /* Claves para Requerimientos tipo correo electronico */
    public static class clavesTemplateAviso
    {
        
        
        /* Carta Ambiental */
        public static String VISACION_CARTA_AMB = "VISACION_CARTA_AMB";
        public static String CORRECCION_DE_CARTA_MO = "CORRECCION_DE_CARTA_MO";
        public static String CARTA_AMB_FIRMA_JEFATURA = "CARTA_AMB_FIRMA_JEFATURA";

        /* Planos */
        public static String VISACION_CARTA_PLANO = "VISACION_CARTA_PLANO";
        public static String VISACION_CARTA_CORRIGE_PLANO = "VISACION_CARTA_CORRIGE_PLANO";
        public static String CARTA_PLANO_PARA_FIRMA_JEFATURA = "CARTA_PLANO_PARA_FIRMA_JEFATURA";
        public static String CARTA_CORRIGE_PLANO_PARA_FIRMA_JEFATURA = "CARTA_CORRIGE_PLANO_PARA_FIRMA_JEFATURA";
        public static String CORRECCION_CARTA_PLANO = "CORRECCION_CARTA_PLANO";
        public static String CORRECCION_DE_CARTA_CORRIGE_PLANO = "CORRECCION_DE_CARTA_CORRIGE_PLANO";
        public static String CORRECCION_DE_CARTA_MO_COLECTORES = "CORRECCION_DE_CARTA_MO_COLECTORES";

        /* Informe DAC */
        public static String VISACION_IT_DAC = "VISACION_IT_DAC";
        public static String CORRECCION_DE_IT_DAC = "CORRECCION_DE_IT_DAC";
        public static String IT_DAC_PARA_FIRMA_JEFATURA = "IT_DAC_PARA_FIRMA_JEFATURA";

        
        /* Informe de Cartografía */
        public static String CORRECCION_IT_OUT = "CORRECCION_IT_OUT";
        public static String ACTUALIZACION_IT_UOT = "ACTUALIZACION_IT_UOT";

        
        /* Carta Titular */
        public static String VISACION_CARTA_SEIA = "VISACION_CARTA_SEIA";
        public static String CORRECCION_CARTA_SEIA = "CORRECCION_CARTA_SEIA";
        public static String CARTA_SEIA_PARA_FIRMA_JEFATURA = "CARTA_SEIA_PARA_FIRMA_JEFATURA";
        
        
        /* Claves para el envío de Alertas */
        public static string RESOL_SSP_APRUEBA = "RESOL_SSP_APRUEBA"; //(Alerta 1)
        public static string INFORME_DAC_RES_SSPP_PENDIENTE = "INFORME_DAC_RES_SSPP_PENDIENTE";//(Alerta 2)
        public static string INFORME_TECNICO_DAC_PENDIENTE = "INFORME_TECNICO_DAC_PENDIENTE"; //(Alerta 3)
        public static string REQUERIMIENTO_CAMBIO_ESTADO_PENDIENTE = "REQUERIMIENTO_CAMBIO_ESTADO_PENDIENTE"; //(Alerta 4)
        public static string REQUERIMIENTO_CON_RESPUESTA = "REQUERIMIENTO_CON_RESPUESTA"; //(Alerta 5)
        public static string PERT_SIN_MOVIMIENTO = "PERT_SIN_MOVIMIENTO"; //(Alerta 6)
        public static string INGRESO_NUEVO_PERT = "INGRESO_NUEVO_PERT"; //(Alerta 7)
        public static string CARPETA_NO_ASIGNADA = "CARPETA_NO_ASIGNADA"; //(Alerta 8)
        public static string HECTAREAS_UTILIZADAS_RELOCALIZACION = "HECTAREAS_UTILIZADAS_RELOCALIZACION"; //(Alerta 9)
        public static string SOLICITUD_CAMBIA_ESTADO_CON_PLAZO = "SOLICITUD_CAMBIA_ESTADO_CON_PLAZO"; //(Alerta 10)
        public static string SECTOR_RELOCALIZACION_RECHAZADO = "SECTOR_RELOCALIZACION_RECHAZADO"; //(Alerta 11)
        public static string CREAR_CONCESION = "CREAR_CONCESION"; //(Alerta 12)
        public static string MODIFICACION_CONCESION = "MODIFICACION_CONCESION"; //(Alerta 13)
        public static string REGULARIZACION_CONCESION = "REGULARIZACION_CONCESION"; //(Alerta 14)
        public static string RELOCALIZACION_CONCESION = "RELOCALIZACION_CONCESION"; //(Alerta 15)        
        public static string PUBLICACION_RADIAL = "PUBLICACION_RADIAL"; //(Alerta 16)
        public static string PUBLICACION_WEB = "PUBLICACION_WEB"; //(Alerta 17)
        public static string SIN_CERTIFICADO_CAPITANIA_PUERTO = "SIN_CERTIFICADO_CAPITANIA_PUERTO"; //(Alerta 18)
        public static string PLAZOS_VENCIDOS = "PLAZOS_VENCIDOS"; //(Alerta 19)
        public static string SOLICITUD_COLECTOR_EXISTENTE = "SOLICITUD_COLECTOR_EXISTENTE"; //(Alerta 20)
        public static string SOLICITUD_AMERB_NOMBRE_EXISTENTE = "SOLICITUD_AMERB_NOMBRE_EXISTENTE"; //(Alerta 21)
        public static string RECURSO_DE_REPOSICION = "RECURSO_DE_REPOSICION"; //(Alerta 22)
        public static string DOS_MESES_PUBLICACION_RADIAL = "DOS_MESES_PUBLICACION_RADIAL"; //(Alerta 23)

        public static string REITERA_PUBLICACION_WEB = "REITERA_PUBLICACION_WEB";
        public static string REITERA_PUBLICACION_RADIAL = "REITERA_PUBLICACION_RADIAL";
        public static string CORRECCION_PUBLICACION_RADIAL = "CORRECCION_PUBLICACION_RADIAL";
        public static string REITERA_CORRECCION_PUBLICACION_RADIAL = "REITERA_CORRECCION_PUBLICACION_RADIAL";

        public static string INFORME_AMBIENTAL_MO = "INFORME_AMBIENTAL_MO";
        public static string ITC_MO_UOT = "ITC_MO_UOT";

        //Los recursos de reposición en P4 solo son ingresados por la sección de Resolución SSP

        //public static string RECURSO_DE_REPOSICION_PLANOS = "RECURSO_DE_REPOSICION_PLANOS";
        //public static string RECURSO_DE_REPOSICION_INFORME_CARTOGRAFIA = "RECURSO_DE_REPOSICION_INFORME_CARTOGRAFIA";
        //public static string RECURSO_DE_REPOSICION_DIFROL = "RECURSO_DE_REPOSICION_DIFROL";
        //public static string RECURSO_DE_REPOSICION_INFORME_SEA = "RECURSO_DE_REPOSICION_INFORME_SEA";

        public static string ITC_CPS_UOT = "ITC_CPS_UOT";

        public static readonly string EVALUACION_CPS_E_INFAS = "EVALUACION_CPS_E_INFAS";
        public static readonly string DIFUSION_BN_INFORMATIVO = "DIFUSION_BN_INFORMATIVO";

        public static string CREAR_COLECTOR = "CREAR_COLECTOR";
        public static string REQUERIMIENTO_CAMBIO_ESTADO_PENDIENTE_1 = "REQUERIMIENTO_CAMBIO_ESTADO_PENDIENTE_1";
        public static string REQUERIMIENTO_CAMBIO_ESTADO_PENDIENTE_2 = "REQUERIMIENTO_CAMBIO_ESTADO_PENDIENTE_2";


        /* Correos Electrónicos Pullinque 4 */
        public static string CORRECCION_CARTA_CERTIFICADO_DISTANCIA = "CORRECCION_CARTA_CERTIFICADO_DISTANCIA";
        public static string CORRECCION_OFICIO_INSPECCION_TERRENO = "CORRECCION_OFICIO_INSPECCION_TERRENO";
        public static string INSPECCION_TERRENO_PARA_FIRMA_JEFATURA = "INSPECCION_TERRENO_PARA_FIRMA_JEFATURA";
        public static string VISACION_CARTA_DIFROL = "VISACION_CARTA_DIFROL";
        public static string CORRECCION_DIFROL = "CORRECCION_DIFROL";
        public static string DIFROL_PARA_FIRMA_JEFATURA = "DIFROL_PARA_FIRMA_JEFATURA";
        public static string VISACION_CARTA_ANTECEDENTES_COMPLEMENTARIOS = "VISACION_CARTA_ANTECEDENTES_COMPLEMENTARIOS";
        public static string CORRECCION_CARTA_ANTECEDENTES_COMPLEMENTARIOS = "CORRECCION_CARTA_ANTECEDENTES_COMPLEMENTARIOS";
        public static string CARTA_ANTECEDENTES_COMPLEMENTARIOS_FIRMA_JEFATURA = "CARTA_ANTECEDENTES_COMPLEMENTARIOS_FIRMA_JEFATURA";
        public static string VISACION_CARTA_NOTIFICACION_REFORMULACION = "VISACION_CARTA_NOTIFICACION_REFORMULACION";
        public static string CORRECCION_CARTA_NOTIFICACION_REFORMULACION = "CORRECCION_CARTA_NOTIFICACION_REFORMULACION";
        public static string CARTA_NOTIFICACION_REFORMULACION_FIRMA_JEFATURA = "CARTA_NOTIFICACION_REFORMULACION_FIRMA_JEFATURA";
        public static string VISACION_CARTA_NOTIFICACION_POR_INSUFICIENCIA = "VISACION_CARTA_NOTIFICACION_POR_INSUFICIENCIA";
        public static string CORRECCION_CARTA_NOTIFICACION_POR_SUFICIENCIA = "CORRECCION_CARTA_NOTIFICACION_POR_SUFICIENCIA";
        public static string CARTA_NOTIFICACION_POR_INSUFICIENCIA_FIRMA_JEFATURA = "CARTA_NOTIFICACION_POR_INSUFICIENCIA_FIRMA_JEFATURA";
        public static string VISACION_CARTA_DEVOLUCION_ANTICIPADA_POR_INSUFICIENCIA = "VISACION_CARTA_DEVOLUCION_ANTICIPADA_POR_INSUFICIENCIA";
        public static string CORRECCION_CARTA_DEVOLUCION_ANTICIPADA_POR_INSUFICIENCIA = "CORRECCION_CARTA_DEVOLUCION_ANTICIPADA_POR_INSUFICIENCIA";
        public static string CARTA_DEVOLUCION_ANTICIPADA_POR_INSUFICIENCIA_FIRMA_JEFATURA = "CARTA_DEVOLUCION_ANTICIPADA_POR_INSUFICIENCIA_FIRMA_JEFATURA";
        public static string CORRECION_CARTA_PLANOS_UOT = "CORRECION_CARTA_PLANOS_UOT";
        public static string VISACION_CARTA_PLANOS_UTS = "VISACION_CARTA_PLANOS_UTS";
        public static string VISACION_CARTA_CORRIGE_PLANOS = "VISACION_CARTA_CORRIGE_PLANOS";
        public static string CORRECCION_CARTA_PLANOS_UTS = "CORRECCION_CARTA_PLANOS_UTS";
        public static string CORRECCION_CARTA_CORRIGE_PLANOS_UTS = "CORRECCION_CARTA_CORRIGE_PLANOS_UTS";
        public static string CARTA_PLANOS_FIRMA_JEFATURA = "CARTA_PLANOS_FIRMA_JEFATURA";
        public static string CARTA_CORRIGE_PLANOS_FIRMA_JEFATURA = "CARTA_CORRIGE_PLANOS_FIRMA_JEFATURA";
        public static string ESPERA_REVISION_PLANOS = "ESPERA_REVISION_PLANOS";
        public static string VISACION_OFICIO_VISACION_PLANOS = "VISACION_OFICIO_VISACION_PLANOS";
        public static string CORRECCION_OFICIO_VISACION_PLANOS = "CORRECCION_OFICIO_VISACION_PLANOS";
        public static string OFICIO_VISACION_PLANOS_FIRMA_JEFATURA = "OFICIO_VISACION_PLANOS_FIRMA_JEFATURA";
        public static string CORRECCION_CARTA_CORRIGE_PLANOS_UOT = "CORRECCION_CARTA_CORRIGE_PLANOS_UOT";
        public static string ANTECEDENTES_AMERB = "ANTECEDENTES_AMERB";
        public static string EVALUACION_AMERB = "EVALUACION_AMERB";
        public static string ANTECEDENTES_DIRECCION_ZONAL = "ANTECEDENTES_DIRECCION_ZONAL";
        public static string VISACION_CARTA_UTS = "VISACION_CARTA_UTS";
        public static string CORRECCION_CARTA_MO_UTS = "CORRECCION_CARTA_MO_UTS";
        public static string VISACION_CARTA_RECOPILACION_CPS_E_INFAS_UOT = "VISACION_CARTA_RECOPILACION_CPS_E_INFAS_UOT";
        public static string CORRECCION_CARTA_RECOPILACION_CPS_E_INFAS_UOT = "CORRECCION_CARTA_RECOPILACION_CPS_E_INFAS_UOT";
        public static string VISACION_CARTA_RECOPILACION_CPS_E_INFAS_UTS = "VISACION_CARTA_RECOPILACION_CPS_E_INFAS_UTS";
        public static string CORRECCION_CARTA_RECOPILACION_CPS_E_INFAS_UTS = "CORRECCION_CARTA_RECOPILACION_CPS_E_INFAS_UTS";
        public static string CARTA_RECOPILACION_CPS_E_INFAS_FIRMA_JEFATURA = "CARTA_RECOPILACION_CPS_E_INFAS_FIRMA_JEFATURA";
        public static string CORRECCION_CARTA_SEIA_UTS = "CORRECCION_CARTA_SEIA_UTS";
        public static string VISACION_CARTA_AMBIENTAL_UTS = "VISACION_CARTA_AMBIENTAL_UTS";
        public static string VISACION_CARTA_TITULAR_UTS = "VISACION_CARTA_TITULAR_UTS";
        public static string VISACION_CERTIFICADO_REGISTRO_OPERACION = "VISACION_CERTIFICADO_REGISTRO_OPERACION";
        public static string CORRECCION_CERTIFICADO_REGISTRO_OPERACION = "CORRECCION_CERTIFICADO_REGISTRO_OPERACION";
        public static string CERTIFICADO_REGISTRO_OPERACION_FIRMA_JEFATURA = "CERTIFICADO_REGISTRO_OPERACION_FIRMA_JEFATURA";
        public static string VISACION_IT_DAC_UTS = "VISACION_IT_DAC_UTS";
        public static string CORRECCION_IT_DAC_UTS = "CORRECCION_IT_DAC_UTS";
        public static string EVALUACION_CARTOGRAFICA = "EVALUACION_CARTOGRAFICA";
        public static string CORRECCION_CARTA_DAC_REFORM_CARTOGRAFICA = "CORRECCION_CARTA_DAC_REFORM_CARTOGRAFICA";
        public static string CARTA_DAC_REFORM_CARTOGRAFICA_PARA_FIRMA_JEFATURA = "CARTA_DAC_REFORM_CARTOGRAFICA_PARA_FIRMA_JEFATURA";
        public static string INFORME_AMBIENTAL_RECOPILACION_CPS_E_INFAS = "INFORME_AMBIENTAL_RECOPILACION_CPS_E_INFAS";
        public static string VISACION_OFICIO_NOTIFICACION_SMA = "VISACION_OFICIO_NOTIFICACION_SMA";
        public static string CORRECCION_OFICIO_NOTIFICACION_SMA = "CORRECCION_OFICIO_NOTIFICACION_SMA";
        public static string OFICIO_NOTIFICACION_SMA_PARA_FIRMA_JEFATURA = "OFICIO_NOTIFICACION_SMA_PARA_FIRMA_JEFATURA";

        public static string CARTA_TITULAR_MO = "CARTA_TITULAR_MO";
        public static string CARTA_SOMETIMIENTO_SEA_RCA = "CARTA_SOMETIMIENTO_SEA_RCA";

        public static string NOTIFICA_ASIGNACION_DE_TRAMITE = "NOTIFICA_ASIGNACION_DE_TRAMITE";

        public static string UNIDAD_DEPENDENCIA_CAMBIA_ESTADO = "UNIDAD_DEPENDENCIA_CAMBIA_ESTADO";
        
        //2017
        public static string ASIGNADOR_EVALUCION_CARTO = "ASIGNADOR_EVALUCION_CARTO";
        public static string ACTUALIZACION_CARTO_REPUESTA = "ACTUALIZACION_CARTO_REPUESTA";
        public static string INGRESO_SOLICITUD = "INGRESO_SOLICITUD";
        public static string ASIGNADOR_UA = "ASIGNADOR_UA";
        public static string INICIO_VISACION = "INICIO_VISACION";
        public static string VISACION_SI = "VISACION_SI";
        public static string VISACION_NO = "VISACION_NO";
        public static string SUPEDITADA_TERMINADA_APROBADA = "SUPEDITADA_TERMINADA_APROBADA";
        public static string SUPEDITADA_TERMINADA_RECHAZADA = "SUPEDITADA_TERMINADA_RECHAZADA";
        public static string VENCIMIENTO_UE = "VENCIMIENTO_UE";
        public static string SUSPENDIDO_GRUPO_CREADO = "SUSPENDIDO_GRUPO_CREADO";

        public static string VISACION_FIRMA_JEFATURA = "VISACION_FIRMA_JEFATURA";
    }
}
